version: '3'

services:
  db:
    container_name: avido_db
    image: postgres
    volumes:
       - ./docker/db/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    restart: always
    networks:
      - internal

  php:
    container_name: avido_php
    build:
      context: ./
      dockerfile: docker/web.Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

  nginx:
    container_name: avido_nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - php
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
